/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.12.0
 * Tue, 21 Apr 2026 00:15:48 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();
_pGlob.css3Objects = new WeakMap();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        // COMPAT: <4.9.0, old engine, new puzzles
        const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && (isID ? objFound.uuid === objName : objFound.name === objName))
            return objFound;
    
        function findValidByName(obj, objName) {
            if ((isID ? obj.uuid === objName : obj.name === objName) && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function getElement(id, isParent=false) {
        let elem;
        if (Array.isArray(id) && id[0] === 'CONTAINER') {
            if (appInstance !== null) {
                elem = appInstance.container;
            } else if (typeof _initGlob !== 'undefined') {
                // if we are on the initialization stage, we still can have access
                // to the container element
                const contId = _initGlob.container;
                elem = isParent ? parent.document.getElementById(contId)
                        : document.getElementById(contId);
            }
        } else if (Array.isArray(id) && id[0] === 'WINDOW') {
            elem = isParent ? parent : window;
        } else if (Array.isArray(id) && id[0] === 'DOCUMENT') {
            elem = isParent ? parent.document : document;
        } else if (Array.isArray(id) && id[0] === 'BODY') {
            elem = isParent ? parent.document.body : document.body;
        } else if (Array.isArray(id) && (id[0] === 'QUERYSELECTOR' || id[0] === 'QUERYSELECTORALL')) {
            elem = isParent ? parent.document.querySelector(id[1]) : document.querySelector(id[1]);
        } else {
            elem = isParent ? parent.document.getElementById(id) : document.getElementById(id);
        }
        return elem;
    }
        
    function getMaterialEditableTextures(matName, collectSameNameMats=false) {
        let mats = [];
        if (collectSameNameMats) {
            mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
        } else {
            const firstMat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
            if (firstMat !== null) {
                mats = [firstMat];
            }
        }
    
        const textures = mats.reduce((texArray, mat) => {
            let matTextures = [];
            switch (mat.type) {
                case 'MeshNodeMaterial':
                    matTextures = Object.values(mat.nodeTextures);
                    break;
    
                case 'MeshStandardMaterial':
                    matTextures = [
                        mat.map, mat.lightMap, mat.aoMap, mat.emissiveMap,
                        mat.bumpMap, mat.normalMap, mat.displacementMap,
                        mat.roughnessMap, mat.metalnessMap, mat.alphaMap, mat.envMap
                    ];
                    break;
    
                default:
                    console.error('getMaterialEditableTextures: Unknown material type '
                            + mat.type);
                    break;
            }
    
            Array.prototype.push.apply(texArray, matTextures);
            return texArray;
        }, []);
    
        return textures.filter(elem => {
            // check Texture type exactly
            return elem && (elem.constructor === v3d.Texture
                    || elem.constructor === v3d.CompressedTexture
                    || elem.constructor === v3d.DataTexture
                    || elem.constructor === v3d.CanvasTexture
                    || elem.constructor === v3d.VideoTexture);
        });
    }
        
    function replaceMaterialEditableTexture(mat, oldTex, newTex) {
        if (v3d.MaterialUtils.replaceTexture) {
            v3d.MaterialUtils.replaceTexture(mat, oldTex, newTex);
            return;
        }
    
        // COMPAT: <4.8, had no replaceTexture() method
        switch (mat.type) {
            case 'MeshNodeMaterial':
                // NOTE: replace in node graph as well since it's possible to texture get lost
                // after updateNodeGraph()
                mat.traverseNodes(node => {
                    if (node.originData.texture === oldTex)
                        node.originData.texture = newTex;
                });
    
                for (const name in mat.nodeTextures) {
                    if (mat.nodeTextures[name] === oldTex) {
                        mat.nodeTextures[name] = newTex;
                    }
                }
                break;
    
            case 'MeshStandardMaterial':
                const texNames = ['map', 'lightMap', 'aoMap', 'emissiveMap',
                        'bumpMap', 'normalMap', 'displacementMap', 'roughnessMap',
                        'metalnessMap', 'alphaMap', 'envMap'];
    
                texNames.forEach(name => {
                    if (mat[name] === oldTex) {
                        mat[name] = newTex;
                    }
                });
                break;
    
            default:
                console.error('replaceMaterialEditableTexture: Unsupported material type '
                        + mat.type);
                break;
        }
    
        // inherit some save params
        newTex.encoding = oldTex.encoding;
        newTex.wrapS = oldTex.wrapS;
        newTex.wrapT = oldTex.wrapT;
    }

    return {
        getObjectByName, bindListener, getElement, getMaterialEditableTextures,
        replaceMaterialEditableTexture,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};

PL.loadedLibraries = PL.loadedLibraries || [];



PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    // initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = true;
_initGlob.output.initOptions.useFullscreen = false;

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}



var PROC = {
    
};

var VARS = Object.defineProperties({}, {
    '\'geometrySpeed\'': { get: function() { return _geometrySpeed_; }, set: function(val) { _geometrySpeed_ = val; } },
    'geometrySpeed': { get: function() { return geometrySpeed; }, set: function(val) { geometrySpeed = val; } },
});

var _geometrySpeed_, geometrySpeed;

// setActiveCamera puzzle
function setActiveCamera(camName) {
    var camera = PzLib.getObjectByName(camName);
    if (!camera || !camera.isCamera || appInstance.getCamera() == camera)
        return;
    appInstance.setCamera(camera);
}

// initFullscreen puzzle
function initFullscreen(id, isParent, enterCb, exitCb, unavailCb) {
    const elem = PzLib.getElement(id, isParent);
    if (!elem)
        return;

    const doc = isParent ? parent.document : document;
    if (!(doc.fullscreenEnabled || doc.webkitFullscreenEnabled)) {
        unavailCb();
        return;
    }

    function fullscreenClickCb() {
        event.stopPropagation();
        if (doc.fullscreenElement || doc.webkitFullscreenElement) {
            exitFullscreen();
        } else {
            requestFullscreen(doc.body);
        }
    }
    PzLib.bindListener(elem, 'click', fullscreenClickCb);

    function changeFullscreen(event) {
        if (doc.fullscreenElement || doc.webkitFullscreenElement)
            enterCb(event);
        else
            exitCb(event);
    }

    PzLib.bindListener(doc, 'webkitfullscreenchange', changeFullscreen);
    PzLib.bindListener(doc, 'fullscreenchange', changeFullscreen);

    function requestFullscreen(fselem) {
        if (fselem.requestFullscreen)
            fselem.requestFullscreen();
        else if (fselem.webkitRequestFullscreen)
            fselem.webkitRequestFullscreen();
    }
    function exitFullscreen() {
        if (doc.exitFullscreen)
            doc.exitFullscreen();
        else if (doc.webkitExitFullscreen)
            doc.webkitExitFullscreen();
    }
}

// createCanvasElem puzzle
function createCanvasElem(id, width, height) {
    var elem = document.createElement('canvas');

    elem.id = id;
    elem.width = width;
    elem.height = height;

    return elem;
}

// replaceTexture puzzle
function replaceTexture(matName, texName, texUrlOrElem, noSharing, doCb) {

    const textures = PzLib.getMaterialEditableTextures(matName, true).filter(function(elem) {
        return elem.name == texName;
    });

    if (!textures.length)
        return;

    const mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);

    if (texUrlOrElem instanceof Promise) {

        texUrlOrElem.then(function(response) {
           processImageUrl(response);
        }, function(error) {});

    } else if (typeof texUrlOrElem == 'string') {

        processImageUrl(texUrlOrElem);

    /**
     * NOTE: not checking for the PzLib.MediaHTML5 constructor, because otherwise this
     * puzzle would always provide the code that's not needed most of the time
     */
    } else if (texUrlOrElem instanceof Object && texUrlOrElem.source
            instanceof HTMLVideoElement) {

        processVideo(texUrlOrElem.source);

    } else if (texUrlOrElem instanceof HTMLCanvasElement) {

        processCanvas(texUrlOrElem);

    } else {

        return;

    }

    function processImageUrl(url) {

        const isHDR = (url.search(/\.hdr$/) > 0);
        const isComp = (url.search(/\.ktx2/) > 0);

        let isCompOld = false;
        let isVideoOld = false;
        textures.forEach(function(elem) {
            if (elem.isCompressedTexture)
                isCompOld = true;
            if (elem.isVideoTexture)
                isVideoOld = true;
        });

        let loader;

        if (!isHDR && !isComp && !isCompOld && !isVideoOld) {
            loader = new v3d.ImageLoader();
            loader.setCrossOrigin('Anonymous');
        } else if (isComp) {
            loader = appInstance.loader.ktx2Loader;
            loader.setCrossOrigin('Anonymous');
        } else if (isCompOld || isVideoOld) {
            loader = new v3d.TextureLoader();
            loader.setCrossOrigin('Anonymous');
        } else {
            loader = new v3d.FileLoader();
            loader.setResponseType('arraybuffer');
        }

        loader.load(url, function(loadedData) {

            textures.forEach(function(oldTex) {
                oldTex.dispose();

                let newTex;

                if (!isHDR && !isComp && !isCompOld && !isVideoOld) {

                    if (noSharing) {
                        newTex = oldTex.clone();
                        mats.forEach(function(mat) {
                            PzLib.replaceMaterialEditableTexture(mat, oldTex, newTex);
                            mat.needsUpdate = true;
                        });
                    } else {
                        newTex = oldTex;
                    }

                    newTex.source = new v3d.Source(loadedData);

                } else if (isComp || isCompOld || isVideoOld) {

                    newTex = loadedData;

                    mats.forEach(function(mat) {
                        newTex.flipY = false;
                        newTex.name = texName;
                        PzLib.replaceMaterialEditableTexture(mat, oldTex, newTex);
                        mat.needsUpdate = true;
                        // HACK: to return back encoding in nodes, workaround for https://crbug.com/1256340
                        if (mat.isMeshNodeMaterial)
                            mat.updateNodeGraph(true);
                    });

                } else {
                    // parse loaded HDR buffer
                    const rgbeLoader = new v3d.RGBELoader();
                    const texData = rgbeLoader.parse(loadedData);

                    if (noSharing) {
                        newTex = oldTex.clone();
                        mats.forEach(function(mat) {
                            PzLib.replaceMaterialEditableTexture(mat, oldTex, newTex);
                            mat.needsUpdate = true;
                        });
                    } else {
                        newTex = oldTex;
                    }

                    newTex.source = new v3d.Source({
                        data: texData.data,
                        width: texData.width,
                        height: texData.height
                    });

                    newTex.magFilter = v3d.LinearFilter;
                    newTex.minFilter = v3d.LinearFilter;
                    newTex.generateMipmaps = false;
                    newTex.isDataTexture = true;
                }

                // update world material if it is using this texture
                if (appInstance.scene !== null && appInstance.scene.worldMaterial !== null) {
                    var wMat = appInstance.scene.worldMaterial;
                    for (let texName in wMat.nodeTextures) {
                        if (wMat.nodeTextures[texName] == newTex) {
                            appInstance.updateEnvironment(wMat);
                        }
                    }
                }
            });

            // exec once
            doCb();

        });
    }

    function processVideo(elem) {
        const videoTex = new v3d.VideoTexture(elem);
        videoTex.flipY = false;
        videoTex.name = texName;

        let videoAssigned = false;

        var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
        mats.forEach(function(mat) {

            textures.forEach(function(tex) {
                PzLib.replaceMaterialEditableTexture(mat, tex, videoTex);
            });

            mat.needsUpdate = true;
            // HACK: to assign new encoding in nodes, workaround for https://crbug.com/1256340
            if (mat.isMeshNodeMaterial) {
                if (v3d.engineVersionCmp('4.9.0', v3d.REVISION) >= 0) {
                    mat.updateNodeGraph(true);
                } else {
                    // COMPAT: <4.9.0, new puzzles, old engine
                    // HACK: preserve links to uniform arrays which got replaced in updateNodeGraph()
                    const nodeRGBArrSave = mat.nodeRGBArr;
                    const nodeValueSave = mat.nodeValue;
                    mat.updateNodeGraph();
                    mat.nodeRGBArr = nodeRGBArrSave;
                    mat.nodeValue = nodeValueSave;
                }
            }

            videoAssigned = true;
        });

        if (videoAssigned) {
            if (elem.readyState < 1) {
                PzLib.bindListener(elem, 'loadedmetadata', doCb);
            } else {
                doCb();
            }
        }

    }

    function processCanvas(elem) {
        const canvasTex = new v3d.CanvasTexture(elem);
        canvasTex.flipY = false;
        canvasTex.name = texName;

        let canvasAssigned = false;

        var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
        mats.forEach(function(mat) {

            textures.forEach(function(tex) {
                PzLib.replaceMaterialEditableTexture(mat, tex, canvasTex);
            });

            mat.needsUpdate = true;
            canvasAssigned = true;
        });

        if (canvasAssigned) {

            if (PL) {
                PL.canvasTextures = PL.canvasTextures || {};
                PL.canvasTextures[canvasTex.image.id] = canvasTex;
            }

            doCb();
        }

    }
}

// setInterval puzzle
function registerInterval(timeout, callback) {
    var timerId = window.setInterval(function() { callback(timerId) }, 1000 * timeout);
}

// everyFrame puzzle
function registerEveryFrame(callback) {
    if (typeof callback == 'function') {
        appInstance.renderCallbacks.push(callback);
        if (PL.editorRenderCallbacks)
            PL.editorRenderCallbacks.push([appInstance, callback]);
    }
}

// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}


setActiveCamera('<none>');

initFullscreen('myElem', false, function() {}, function() {}, function() {});

replaceTexture('canvas', 'uv_grid.jpg', createCanvasElem('geometry_canvas', 512, 512), false, function() {});

registerInterval(0.1, function() {});

registerInterval(1, function() {});

_geometrySpeed_;

appInstance.clock.elapsedTime;

Math.sin(appInstance.clock.elapsedTime / 180 * Math.PI);

0.1;

registerSetTimeout(1, function() {
    _geometrySpeed_ = 1;
    geometrySpeed = 0.2;
    registerEveryFrame(function() {

        Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('function runCode(app, puzzles) {' + '\n' +
        '    const obj = app.scene.getObjectByName(\'plane\'); // 替换为你的对象名' + '\n' +
        '    ' + '\n' +
        '    // Fragment shader (你的原代码，添加uniform声明)' + '\n' +
        '    const fragmentShader = `' + '\n' +
        '#ifdef GL_ES' + '\n' +
        'precision mediump float;' + '\n' +
        '#endif' + '\n' +
        '' + '\n' +
        '#define PI 3.1415926535897932384626433832795' + '\n' +
        '' + '\n' +
        'uniform float iTime;' + '\n' +
        'uniform vec3 iResolution;' + '\n' +
        '' + '\n' +
        'varying vec2 vUv;' + '\n' +
        '' + '\n' +
        'const float wave_amplitude = 0.076;' + '\n' +
        'const float period = 2.*PI;' + '\n' +
        '' + '\n' +
        'float wave_phase() {' + '\n' +
        '    return iTime;' + '\n' +
        '}' + '\n' +
        '' + '\n' +
        'float square(vec2 st) {' + '\n' +
        '    vec2 bl = step(vec2(0.), st);' + '\n' +
        '    vec2 tr = step(vec2(0.),1.0-st);' + '\n' +
        '    return bl.x * bl.y * tr.x * tr.y;' + '\n' +
        '}' + '\n' +
        '' + '\n' +
        'vec4 frame(vec2 st) {' + '\n' +
        '    float tushka = square(st*mat2((1./.48), 0., 0., (1./.69)));' + '\n' +
        '    ' + '\n' +
        '    mat2 sector_mat = mat2(1./.16, 0., 0., 1./.22);' + '\n' +
        '    float sectors[4];' + '\n' +
        '    sectors[0] = square(st * sector_mat + (1./.16)*vec2(0.000,-0.280));' + '\n' +
        '    sectors[1] = square(st * sector_mat + (1./.16)*vec2(0.000,-0.060));' + '\n' +
        '    sectors[2] = square(st * sector_mat + (1./.16)*vec2(-0.240,-0.280));' + '\n' +
        '    sectors[3] = square(st * sector_mat + (1./.16)*vec2(-0.240,-0.060));' + '\n' +
        '    vec3 sector_colors[4];' + '\n' +
        '    sector_colors[0] = vec3(0.941, 0.439, 0.404) * sectors[0];' + '\n' +
        '    sector_colors[1] = vec3(0.435, 0.682, 0.843) * sectors[1];' + '\n' +
        '    sector_colors[2] = vec3(0.659, 0.808, 0.506) * sectors[2];' + '\n' +
        '    sector_colors[3] = vec3(0.996, 0.859, 0.114) * sectors[3];' + '\n' +
        '    ' + '\n' +
        '    return vec4(vec3(sector_colors[0] + sector_colors[1] +' + '\n' +
        '                     sector_colors[2] + sector_colors[3]), tushka);' + '\n' +
        '}' + '\n' +
        '' + '\n' +
        'vec4 trail_piece(vec2 st, vec2 index, float scale) {' + '\n' +
        '    scale = index.x * 0.082 + 0.452;' + '\n' +
        '    ' + '\n' +
        '    vec3 color;' + '\n' +
        '    if (index.y > 0.9 && index.y < 2.1 ) {' + '\n' +
        '        color = vec3(0.435, 0.682, 0.843);' + '\n' +
        '        scale *= .8;' + '\n' +
        '    } else if (index.y > 3.9 && index.y < 5.1) {' + '\n' +
        '        color = vec3(0.941, 0.439, 0.404);' + '\n' +
        '        scale *= .8;' + '\n' +
        '    } else {' + '\n' +
        '        color = vec3(0., 0., 0.);' + '\n' +
        '    }' + '\n' +
        '    ' + '\n' +
        '    float scale1 = 1./scale;' + '\n' +
        '    float shift = - (1.-scale) / (2. * scale);' + '\n' +
        '    vec2 st2 = vec2(vec3(st, 1.) * mat3(scale1, 0., shift, 0., scale1, shift, 0., 0., 1.));' + '\n' +
        '    float mask = square(st2);' + '\n' +
        '' + '\n' +
        '    return vec4( color, mask );' + '\n' +
        '}' + '\n' +
        '' + '\n' +
        'vec4 trail(vec2 st) {' + '\n' +
        '    const float piece_height = 7. / .69;' + '\n' +
        '    const float piece_width = 6. / .54;' + '\n' +
        '  ' + '\n' +
        '    st.x = 1.2760 * pow(st.x, 3.0) - 1.4624 * st.x*st.x + 1.4154 * st.x;' + '\n' +
        '    ' + '\n' +
        '    float x_at_cell = floor(st.x*piece_width)/piece_width;' + '\n' +
        '    float x_at_cell_center = x_at_cell + 0.016;' + '\n' +
        '    float incline = cos(0.5*period + wave_phase()) * wave_amplitude;' + '\n' +
        '    ' + '\n' +
        '    float offset = sin(x_at_cell_center*period + wave_phase())* wave_amplitude + ' + '\n' +
        '        incline*(st.x-x_at_cell)*5.452;' + '\n' +
        '    ' + '\n' +
        '    float mask = step(offset, st.y) * (1.-step(.69+offset, st.y)) * step(0., st.x);' + '\n' +
        '    ' + '\n' +
        '    vec2 cell_coord = vec2((st.x - x_at_cell) * piece_width,' + '\n' +
        '                           fract((st.y-offset) * piece_height));' + '\n' +
        '    vec2 cell_index = vec2(x_at_cell * piece_width, ' + '\n' +
        '                           floor((st.y-offset) * piece_height));' + '\n' +
        '    ' + '\n' +
        '    vec4 pieces = trail_piece(cell_coord, cell_index, 0.752);' + '\n' +
        '    ' + '\n' +
        '    return vec4(vec3(pieces), pieces.a * mask);' + '\n' +
        '}' + '\n' +
        '' + '\n' +
        'vec4 logo(vec2 st) {' + '\n' +
        '    if (st.x <= .54) {' + '\n' +
        '        return trail(st);' + '\n' +
        '    } else {' + '\n' +
        '        vec2 st2 = st + vec2(0., -sin(st.x*period + wave_phase())*wave_amplitude);' + '\n' +
        '        return frame(st2 + vec2(-.54, 0));' + '\n' +
        '    }' + '\n' +
        '}' + '\n' +
        '' + '\n' +
        'void main() {' + '\n' +
        '    vec2 st = vUv;' + '\n' +
        '    st.x *= iResolution.x/iResolution.y;' + '\n' +
        '' + '\n' +
        '    st += vec2(.0);' + '\n' +
        '    st *= 1.472;' + '\n' +
        '    st += vec2(-0.7,-0.68);' + '\n' +
        '    float rot = PI*-0.124;' + '\n' +
        '    st *= mat2(cos(rot), sin(rot), -sin(rot), cos(rot));' + '\n' +
        '    vec3 color = vec3(1.);' + '\n' +
        '    ' + '\n' +
        '    vec4 logo_ = logo(st);    ' + '\n' +
        '    gl_FragColor = mix(vec4(0.,.5,.5,1.000), logo_, logo_.a);' + '\n' +
        '}' + '\n' +
        '    `;' + '\n' +
        '    ' + '\n' +
        '    // Vertex shader (简单pass UV)' + '\n' +
        '    const vertexShader = `' + '\n' +
        'varying vec2 vUv;' + '\n' +
        'void main() {' + '\n' +
        '    vUv = uv;' + '\n' +
        '    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);' + '\n' +
        '}' + '\n' +
        '    `;' + '\n' +
        '    ' + '\n' +
        '    obj.material = new v3d.ShaderMaterial({' + '\n' +
        '        uniforms: {' + '\n' +
        '            iTime: { value: 0.0 },' + '\n' +
        '            iResolution: { value: new v3d.Vector3() }' + '\n' +
        '        },' + '\n' +
        '        vertexShader: vertexShader,' + '\n' +
        '        fragmentShader: fragmentShader' + '\n' +
        '    });' + '\n' +
        '    ' + '\n' +
        '    // 动画更新循环' + '\n' +
        '    app.addEventListener(\'loop\', function(e) {' + '\n' +
        '        obj.material.uniforms.iTime.value = e.clock.elapsedTime;' + '\n' +
        '        obj.material.uniforms.iResolution.value.set(' + '\n' +
        '            app.renderer.domElement.width,' + '\n' +
        '            app.renderer.domElement.height,' + '\n' +
        '            1' + '\n' +
        '        );' + '\n' +
        '    });' + '\n' +
        '}')))(appInstance, v3d, PL, VARS, PROC);

    });
});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
